package org.netbeans.gradle.project.properties.global;

import java.net.URL;
import org.netbeans.gradle.project.properties.EnumCombo;
import org.netbeans.gradle.project.properties.ModelLoadingStrategy;
import org.netbeans.gradle.project.util.NbFileUtils;

@SuppressWarnings("serial")
public class BuildScriptParsingPanel extends javax.swing.JPanel implements GlobalSettingsEditor {
    private static final URL HELP_URL = NbFileUtils.getSafeURL("https://github.com/kelemen/netbeans-gradle-project/wiki/Build-Script-Parsing");

    private final EnumCombo<ModelLoadingStrategy> modelLoadingStrategy;

    public BuildScriptParsingPanel() {
        initComponents();

        modelLoadingStrategy = new EnumCombo<>(ModelLoadingStrategy.class, ModelLoadingStrategy.NEWEST_POSSIBLE, jModelLoadStrategy);
    }

    @Override
    public void updateSettings(GlobalGradleSettings globalSettings) {
        modelLoadingStrategy.setSelectedValue(globalSettings.modelLoadingStrategy().getValue());
        jLoadRootProjectFirst.setSelected(globalSettings.loadRootProjectFirst().getValue());
        jReliableJavaVersionCheck.setSelected(globalSettings.mayRelyOnJavaOfScript().getValue());
    }

    @Override
    public void saveSettings(GlobalGradleSettings globalSettings) {
        globalSettings.modelLoadingStrategy().setValue(modelLoadingStrategy.getSelectedValue());
        globalSettings.loadRootProjectFirst().setValue(jLoadRootProjectFirst.isSelected());
        globalSettings.mayRelyOnJavaOfScript().setValue(jReliableJavaVersionCheck.isSelected());
    }

    @Override
    public SettingsEditorProperties getProperties() {
        SettingsEditorProperties.Builder result = new SettingsEditorProperties.Builder(this);
        result.setHelpUrl(HELP_URL);

        return result.create();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jModelLoadStrategy = new javax.swing.JComboBox<>();
        jModelLoadStrategyLabel = new javax.swing.JLabel();
        jReliableJavaVersionCheck = new javax.swing.JCheckBox();
        jLoadRootProjectFirst = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jModelLoadStrategyLabel, org.openide.util.NbBundle.getMessage(BuildScriptParsingPanel.class, "BuildScriptParsingPanel.jModelLoadStrategyLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jReliableJavaVersionCheck, org.openide.util.NbBundle.getMessage(BuildScriptParsingPanel.class, "BuildScriptParsingPanel.jReliableJavaVersionCheck.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLoadRootProjectFirst, org.openide.util.NbBundle.getMessage(BuildScriptParsingPanel.class, "BuildScriptParsingPanel.jLoadRootProjectFirst.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jModelLoadStrategyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModelLoadStrategy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jReliableJavaVersionCheck)
                    .addComponent(jLoadRootProjectFirst))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModelLoadStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jModelLoadStrategyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLoadRootProjectFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jReliableJavaVersionCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jLoadRootProjectFirst;
    private javax.swing.JComboBox<EnumCombo.Item<ModelLoadingStrategy>> jModelLoadStrategy;
    private javax.swing.JLabel jModelLoadStrategyLabel;
    private javax.swing.JCheckBox jReliableJavaVersionCheck;
    // End of variables declaration//GEN-END:variables
}
