package org.netbeans.gradle.project.properties.global;

import java.net.URL;
import org.netbeans.gradle.project.properties.DebugModeCombo;
import org.netbeans.gradle.project.util.NbFileUtils;

@SuppressWarnings("serial")
public class DebuggerPanel extends javax.swing.JPanel implements GlobalSettingsEditor {
    private static final URL HELP_URL = NbFileUtils.getSafeURL("https://github.com/kelemen/netbeans-gradle-project/wiki/Debug-Settings");

    private final DebugModeCombo debugModeHandler;

    public DebuggerPanel() {
        initComponents();
        this.debugModeHandler = new DebugModeCombo(jDebugMode);
    }

    @Override
    public void updateSettings(GlobalGradleSettings globalSettings) {
        DebugMode debugMode = globalSettings.debugMode().getValue();
        debugModeHandler.setSelectedDebugMode(debugMode);
    }

    @Override
    public void saveSettings(GlobalGradleSettings globalSettings) {
        globalSettings.debugMode().setValue(debugModeHandler.getSelectedDebugMode());
    }

    @Override
    public SettingsEditorProperties getProperties() {
        SettingsEditorProperties.Builder result = new SettingsEditorProperties.Builder(this);
        result.setHelpUrl(HELP_URL);

        return result.create();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDebugMode = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDebugMode, 0, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDebugMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<DebugModeCombo.Item> jDebugMode;
    // End of variables declaration//GEN-END:variables
}
