package org.netbeans.gradle.project.properties.ui;

import java.net.URL;
import javax.swing.JCheckBox;
import org.netbeans.gradle.project.api.config.ActiveSettingsQuery;
import org.netbeans.gradle.project.api.config.PropertyReference;
import org.netbeans.gradle.project.api.config.ui.ProfileEditor;
import org.netbeans.gradle.project.api.config.ui.ProfileEditorFactory;
import org.netbeans.gradle.project.api.config.ui.ProfileInfo;
import org.netbeans.gradle.project.api.config.ui.StoredSettings;
import org.netbeans.gradle.project.properties.global.CommonGlobalSettings;
import org.netbeans.gradle.project.properties.global.GlobalSettingsPage;
import org.netbeans.gradle.project.util.NbFileUtils;

@SuppressWarnings("serial")
public class BuildScriptParsingPanel extends javax.swing.JPanel implements ProfileEditorFactory {
    private static final URL HELP_URL = NbFileUtils.getSafeURL("https://github.com/kelemen/netbeans-gradle-project/wiki/Build-Script-Parsing");

    public BuildScriptParsingPanel() {
        initComponents();
    }

    public static GlobalSettingsPage createSettingsPage() {
        GlobalSettingsPage.Builder result = new GlobalSettingsPage.Builder(new BuildScriptParsingPanel());
        result.setHelpUrl(HELP_URL);
        return result.create();
    }

    @Override
    public ProfileEditor startEditingProfile(ProfileInfo profileInfo, ActiveSettingsQuery profileQuery) {
        return new PropertyRefs(profileQuery);
    }

    private void displayCheck(JCheckBox checkbox, Boolean value, PropertyReference<Boolean> propertyRef) {
        displayCheck(checkbox, value != null ? value : propertyRef.getActiveValue());
    }

    private void displayCheck(JCheckBox checkbox, Boolean value) {
        if (value != null) {
            checkbox.setSelected(value);
        }
    }

    private final class PropertyRefs implements ProfileEditor {
        private final PropertyReference<Boolean> loadRootProjectFirstRef;

        public PropertyRefs(ActiveSettingsQuery settingsQuery) {
            loadRootProjectFirstRef = CommonGlobalSettings.loadRootProjectFirst(settingsQuery);
        }

        @Override
        public StoredSettings readFromSettings() {
            return new StoredSettingsImpl(this);
        }

        @Override
        public StoredSettings readFromGui() {
            return new StoredSettingsImpl(this, BuildScriptParsingPanel.this);
        }
    }

    private class StoredSettingsImpl implements StoredSettings {
        private final PropertyRefs properties;

        private final Boolean loadRootProjectFirst;

        public StoredSettingsImpl(PropertyRefs properties) {
            this.properties = properties;

            this.loadRootProjectFirst = properties.loadRootProjectFirstRef.tryGetValueWithoutFallback();
        }

        public StoredSettingsImpl(PropertyRefs properties, BuildScriptParsingPanel panel) {
            this.properties = properties;

            this.loadRootProjectFirst = panel.jLoadRootProjectFirst.isSelected();
        }

        @Override
        public void displaySettings() {
            displayCheck(jLoadRootProjectFirst, loadRootProjectFirst, properties.loadRootProjectFirstRef);
        }

        @Override
        public void saveSettings() {
            properties.loadRootProjectFirstRef.setValue(loadRootProjectFirst);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoadRootProjectFirst = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLoadRootProjectFirst, org.openide.util.NbBundle.getMessage(BuildScriptParsingPanel.class, "BuildScriptParsingPanel.jLoadRootProjectFirst.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLoadRootProjectFirst)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLoadRootProjectFirst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jLoadRootProjectFirst;
    // End of variables declaration//GEN-END:variables
}
